apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/capt2101akash/kubernetes-cluster-setup:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/capt2101akash/kubernetes-cluster-setup:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: kubernetes-cluster-setup
        chartPath: charts/kubernetes-cluster-setup
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/capt2101akash/kubernetes-cluster-setup"
          image.tag: "{{.DIGEST_HEX}}"
