apiVersion: v1
kind: ReplicationController
metadata:
  name: mosquitto-v0
  labels:
    app: mosquitto
    version: v0
spec:
  replicas: 3
  selector:
    app: mosquitto
    version: v0
  template:
    metadata:
      labels:
        app: mosquitto
        version: v0
    spec:
      containers:
      - name: mosquitto
        image: toke/mosquitto
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 0.5
            memory: 500Mi
        volumeMounts:
        - name: mosquitto-data
          mountPath: /etc/mosquitto
        ports:
        - containerPort: 1883
          name: mosquitto
      volumes:
      - name: mosquitto-data
        persistentVolumeClaim:
          claimName: mosquitto-data
