---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
  labels:
    name: mosquitto
spec:
  ports:
  - port: 1883
    name: mqtt-port
    protocol: TCP
  selector:
    app: mosquitto
    id: "1"
  type: LoadBalancer
