apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mosquitto2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: toke/mosquitto
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 0.5
            memory: 500Mi
        ports:
        - containerPort: 1883
        - containerPort: 9001
        volumeMounts:
        - name: nfs
          mountPath: /usr/share/mqtt/data
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: mosquitto-data
          # persistentVolumeClaim:
          #claimName: mosquitto-data
