---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
  labels:
    name: mosquitto
spec:
  ports:
  - port: 80
    name: mqtt-port
    protocol: TCP
    targetPort: 1883
  selector:
    app: mosquitto
    id: "1"
  type: LoadBalancer
  #loadBalancerIP: 35.229.39.135 
