apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto-data
spec:
  capacity:
    storage: 2G
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.233.12.137
            #hostPath:
    path: "/exports"
