apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto
spec:
  capacity:
    storage: 15Mi
  accessModes:
    - ReadOnlyMany
  nfs:
    path: /mnt/fileserv/kubernetes/mosquitto/config
    server: 10.142.0.4
